services:
  - type: web
    name: tg-music-player
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      cd .. && npm install && npm run build
    startCommand: python backend/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
